### ISSUE TITLE
学习和总结文章 todo list

### ISSUE THREAD

**Issue by samonxian** [xianshannan/blog#1]
- [x] JavaScript 之错误异常处理
  需要后续讨论如何处理错误信息
- [x] 怎样才算函数式编程？
- [x] JavaScript 之模拟 new 用法
- [x] 10 分钟带你熟悉浏览器 Http 缓存机制
- [x] 浏览器页面包括哪些线程？
- [x] 如何控制概率进行随机抽奖？
- [ ] 移动端 Hybrid 混合开发入门
   http://www.alloyteam.com/2013/12/web-cache-6-hybrid-app-tailored-cache/
- [ ] Vue 学习篇
  - Vue 组件生命周期钩子函数
  - Vue 指令生命周期钩子函数
  - Vue 核心概念之插槽
  - Vue 组件间通信方式
  - Vue 一些需要注意的地方
  - Vue 核心概念之指令
  - new Vue 发生了什么
- [ ] 深入了解前端内存泄露
- [ ] SSR 服务端渲染实践总结
- [ ] 如何掌握前端性能相关知识？
- [ ] 从零开始搭建一个前端性能监控平台
- [ ] Url 在浏览器访问到页面渲染的整个流程
- [ ] 如何快速掌握 JavaScript 常用设计模式？
  https://mp.weixin.qq.com/s/WiPwb7AyVlxyr1_kYXt96w
- [ ] 你理解 JavaScript this 对象了吗？
- [ ] 如何设计可复用的组件和高阶组件？
- [ ] JavaScript 之深入理解 Promise 原理
- [ ] JavaScript 之 prototype 深入理解
- [ ] 如何区分进程、线程和协程？
- [ ] React Hooks 使用和深入了解
- [ ] 跨域之 CORS
- [ ] git 常用命令总结
   https://github.com/521xueweihan/git-tips
- [ ] 浏览器之 console 
- [ ] 数据结构之二分法
- [ ] 数据结构之链表
- [ ] 数据结构之链栈
- [ ] 数据结构之列队
- [ ] 数据结构之二叉树
- [ ] redux 源码阅读
- [ ] Express、Koa、redux 的 compose 原理分析和拓展
- [ ] react-redux 源码阅读
- [ ] react-router 源码阅读
- [ ] react 源码阅读
  分多篇阅读总结
- [ ] mbox 源码阅读
- [ ] vue 源码阅读
- [ ] vuex 源码阅读
- [ ] PWA 应用实践总结
- [ ] Serverless 深入了解
- [ ] mse 模拟 flv.js
- [ ] 深入了解资源加载优先级
   https://wicg.github.io/priority-hints/
- [ ] High Performance Browser Networking 阅读
   https://hpbn.co/?utm_source=igvita&utm_medium=referral&utm_campaign=igvita-homepage
   这个可能要到 2020 年了

**Comment by samonxian** [comment]
Vue 学习篇
- [x] Vue 组件生命周期钩子函数
- [x] Vue 核心概念之插槽
- [x] Vue 组件间通信方式
- [x] Vue 一些需要注意的地方
   进行中，不断添加进去

**Comment by samonxian** [comment]
Web 移动端
- [x] px、em、rem 区别
- [x] 为什么会有点击  300ms 延时问题？
- [ ] 移动端适配问题总结（布局相关）
- [ ] 移动端常见兼容问题（js 相关）
- [ ] touch 事件深入学习
- [ ] Hybrid、小程序、Web Native（如 React Native Week）简单原理
- [ ] 实现移动端 H5 视频播放器

**Comment by samonxian** [comment]
Vue 原理篇
- [ ] Vue.use 做了什么？
- [ ] new Vue 发生了什么？
- [ ] 简单实现一个 Vuex
- [ ] template 到 render 函数的过程
- [ ] 简单实现一个 Vue

**Comment by samonxian** [comment]
**微前端学习篇**
- [x] 微前端的学习

**相关文章**
- [微前端如何落地](https://mp.weixin.qq.com/s/I2Y4N0hwugNV2d6Zk6AdMg)
